"""
Django settings for hldjango project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


# EARLY DEFAULT SETTINGS
from lib.jr.jrglobalenv import jrGlobalEnv
# set default value for some environment-supported options, which will be visible to settings_base
jrGlobalEnv.setDefault("JR_DJANGO_DEBUG", True)


# base settings
from .settings_base import *






# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db/hlDjangoDb.sqlite3",
    }
}




# HUEY DB SETUP
# see https://huey.readthedocs.io/en/latest/django.html
HUEY = {
    "huey_class": "huey.SqliteHuey",  # Huey implementation to use.
    "name": "HlHueyDb",
    "filename": BASE_DIR / "db/hlHueyDb.sqlite3",
    "results": True,  # Store return values of tasks.
    "store_none": False,  # If a task returns None, do not save to results.

    # ATTN: controls whether we use queued huey or run tasks immediately
    "immediate": False,

    "utc": True,  # Use UTC for all times internally.
    "connection": {},
    "consumer": {
        "workers": 1,
        "worker_type": "process",
        "initial_delay": 0.1,  # Smallest polling interval, same as -d.
        "backoff": 1.15,  # Exponential backoff using this rate, -b.
        "max_delay": 10.0,  # Max possible polling interval, -m.
        "scheduler_interval": 1,  # Check schedule every second, -s.
        "periodic": True,  # Enable crontab feature.
        "check_worker_health": True,  # Enable worker health checks.
        "health_check_interval": 1,  # Check worker health every second.
    },
    # To run Huey in "immediate" mode with a live storage API, specify
    # immediate_use_memory=False.
    #'immediate_use_memory': False,
}








# now override with any secret settings
# ATTN: WE DO *NOT* load in the secure_secret settings, since those should not be in this build
from .settings_insecure_publicsafe import *
