# Generated by Django 5.1.6 on 2025-03-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_bgglink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bgglink",
            field=models.CharField(
                blank=True, default="", help_text="Bgg Username", max_length=32
            ),
        ),
    ]
