# Generated by Django 5.1.6 on 2025-03-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_bgglink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="bgglink",
            new_name="bggname",
        ),
        migrations.AddField(
            model_name="customuser",
            name="webpage",
            field=models.CharField(
                blank=True, default="", help_text="Web page", max_length=256
            ),
        ),
    ]
