# Generated by Django 5.0.3 on 2024-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="queueStatus",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal build queue stage",
                max_length=32,
            ),
        ),
    ]
