# Generated by Django 5.0.3 on 2024-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_remove_gamefile_label_gamefile_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="gameFileType",
            field=models.CharField(
                choices=[("UP", "User Upload"), ("BT", "Built")],
                default="UP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal comments (optional)",
                max_length=80,
            ),
        ),
    ]
