# Generated by Django 5.0.3 on 2024-04-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_remove_game_queuestatus_game_gamequeuestatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="preferredFormatLayout",
            field=models.CharField(
                choices=[
                    ("SOLOSCR", "Solo for screen (one lead per page; single-sided)"),
                    ("SOLOPRN", "Solo for print (one lead per page; double-sided)"),
                    ("ONECOL", "One column per page (double-sided)"),
                    ("TWOCOL", "Two columns per page (double-sided)"),
                ],
                default="SOLOSCR",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="preferredFormatPaperSize",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11 inches)"),
                    ("A4", "A4 (210 x 297 mm)"),
                    ("B5", "B5 (176 × 250 mm)"),
                    ("A5", "A5 (148 x 210 mm)"),
                ],
                default="LETTER",
                max_length=8,
            ),
        ),
    ]
