# Generated by Django 5.0.3 on 2024-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_rename_gamequeuestatus_game_queuestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="queueDate",
            field=models.DateTimeField(
                blank=True, help_text="When was build queued?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="isPublic",
            field=models.BooleanField(
                help_text="Is game publicly visible?", verbose_name="Is game public?"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(
                help_text="Internal name of the game",
                max_length=50,
                verbose_name="Short name",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="preferredFormatLayout",
            field=models.CharField(
                choices=[
                    ("SOLOSCR", "Solo for screen (one lead per page; single-sided)"),
                    ("SOLOPRN", "Solo for print (one lead per page; double-sided)"),
                    ("ONECOL", "One column per page (double-sided)"),
                    ("TWOCOL", "Two columns per page (double-sided)"),
                ],
                default="SOLOSCR",
                max_length=8,
                verbose_name="Preferred Layout",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="preferredFormatPaperSize",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11 inches)"),
                    ("A4", "A4 (210 x 297 mm)"),
                    ("B5", "B5 (176 × 250 mm)"),
                    ("A5", "A5 (148 x 210 mm)"),
                ],
                default="LETTER",
                max_length=8,
                verbose_name="Preferred paper size",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Game text",
                verbose_name="Full game text",
            ),
        ),
    ]
