# Generated by Django 5.0.3 on 2024-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_game_queuedate_alter_game_ispublic_alter_game_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="gameName",
            field=models.CharField(
                blank=True, default="", help_text="Public name of game", max_length=80
            ),
        ),
    ]
