# Generated by Django 5.0.3 on 2024-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_alter_gamefile_gamefiletype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="needsBuild",
        ),
        migrations.AddField(
            model_name="game",
            name="outOfDateDebug",
            field=models.BooleanField(
                default=True, help_text="Debug files are out of date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="outOfDateDraft",
            field=models.BooleanField(
                default=True, help_text="Draft document set is out of date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="outOfDatePreferred",
            field=models.BooleanField(
                default=True, help_text="Preferred build is out of date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="outOfDatePublished",
            field=models.BooleanField(
                default=True, help_text="Published document set is out of date"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="gameFileType",
            field=models.CharField(
                choices=[
                    ("uploadsStory", "Story upload (image, etc.)"),
                    ("buildDraft", "Build draft file"),
                    ("buildPreferred", "Preferred built file"),
                    ("published", "Published file"),
                    ("buildDebug", "Debug file"),
                ],
                default="uploadsStory",
                max_length=32,
            ),
        ),
    ]
