# Generated by Django 5.0.3 on 2024-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_alter_game_buildresultsjsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lastBuildLog",
            field=models.TextField(blank=True, default="", help_text="Last Build Log"),
        ),
    ]
