# Generated by Django 5.0.3 on 2024-05-29 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0023_game_slug_alter_gamefile_gamefiletype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                default=uuid.uuid4,
                help_text="Unique slug id of the game",
                max_length=128,
                unique=True,
            ),
        ),
    ]
