# Generated by Django 5.0.3 on 2024-05-29 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_game_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                help_text="Unique slug id of the game", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique uuid used for file paths",
            ),
        ),
    ]
