# Generated by Django 5.0.3 on 2024-05-30 21:33

import lib.jr.jrdfuncs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0031_alter_game_subdirname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="buildResultsJson",
        ),
        migrations.AlterField(
            model_name="game",
            name="authors",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Author(s) of game w/emails (parsed from game text)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="buildResultsJsonField",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="All build results as json; this is internal field you should not mess with.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="cautions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Age rage, etc. (parsed from game text)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="difficulty",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Difficulty (parsed from game text)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="duration",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Expected playtime (parsed from game text)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="extraInfo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extra information; credits, links, etc. (parsed from game text)",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="gameName",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Public name of game (parsed from game text)",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="isPublic",
            field=models.BooleanField(
                help_text="Is game publicly visible? If unchecked the game will not be listed on public list of games.",
                verbose_name="Is game public",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="lastBuildLog",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Results of last build; check here for errors.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(
                help_text="Internal name of the game; not used for urls or files; just for author info",
                max_length=50,
                validators=[lib.jr.jrdfuncs.validateName],
                verbose_name="Short name",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="preferredFormatLayout",
            field=models.CharField(
                choices=[
                    ("SOLOSCR", "Solo for screen (one lead per page; single-sided)"),
                    ("SOLOPRN", "Solo for print (one lead per page; double-sided)"),
                    ("ONECOL", "One column per page (double-sided)"),
                    ("TWOCOL", "Two columns per page (double-sided)"),
                ],
                default="SOLOSCR",
                max_length=8,
                verbose_name="Preferred Layout; what you set here is what is used when performing the build preferred action.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="preferredFormatPaperSize",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11 inches)"),
                    ("A4", "A4 (210 x 297 mm)"),
                    ("B5", "B5 (176 × 250 mm)"),
                    ("A5", "A5 (148 x 210 mm)"),
                ],
                default="LETTER",
                max_length=8,
                verbose_name="Preferred paper size; what you set here is what is used when performing the build preferred action.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="settingsStatus",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Parsed settings status (see here for details of error when attempting to parse settings)",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="subdirname",
            field=models.CharField(
                default=lib.jr.jrdfuncs.shortUuidAsStringWithPkPrefix,
                max_length=64,
                unique=True,
                validators=[lib.jr.jrdfuncs.validateName],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subtitle of game (parsed from game text)",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short description (parsed from game text)",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Game text using custom storybook markdown formatting; all other settings are parsed from this.  See docs for syntax.",
                verbose_name="Full game text",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="textHash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Automatically calculated hash of game text; used to detect when game needs rebuilding.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="textHashChangeDate",
            field=models.DateTimeField(
                blank=True,
                help_text="Automatically updated date game text was last changed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title of game (parsed from game text)",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Homepage url (parsed from game text)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version information (parsed from game text)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="versionDate",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version date (parsed from game text)",
                max_length=64,
            ),
        ),
    ]
