# Generated by Django 5.0.3 on 2024-05-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0032_remove_game_buildresultsjson_alter_game_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="settingsStatus",
        ),
    ]
