# Generated by Django 5.0.3 on 2024-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0033_remove_game_settingsstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buildResultsJsonField",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="All build results as json; this is internal field you should not mess with.",
                null=True,
            ),
        ),
    ]
