# Generated by Django 5.0.3 on 2024-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0036_game_extracredits_alter_game_extrainfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="List of additional instructions and downloads needed to play, in Markdown format.",
                verbose_name="Additional requirements",
            ),
        ),
    ]
