# Generated by Django 5.0.3 on 2024-12-30 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0038_game_status_alter_game_instructions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="editors",
            field=models.ManyToManyField(
                related_name="editable_objects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
