# Generated by Django 5.0.3 on 2025-01-29 00:55

import lib.jr.jrdfuncs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0039_game_editors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editable_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Additional users who may edit game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique slug id of the game",
                max_length=128,
                unique=True,
                verbose_name="Url slug name",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="subdirname",
            field=models.CharField(
                default=lib.jr.jrdfuncs.shortUuidAsStringWithPkPrefix,
                max_length=64,
                unique=True,
                validators=[lib.jr.jrdfuncs.validateName],
                verbose_name="Subdirectory name",
            ),
        ),
    ]
