# Generated by Django 5.0.3 on 2025-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0040_alter_game_editors_alter_game_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cautions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Age rage, etc. (parsed from game text)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subtitle of game (parsed from game text)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title of game (parsed from game text)",
                max_length=255,
            ),
        ),
    ]
