# Generated by Django 5.1.6 on 2025-02-13 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_alter_game_cautions_alter_game_subtitle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editable_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Allow these additional users to edit this game",
            ),
        ),
    ]
