# Generated by Django 5.1.6 on 2025-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_alter_game_editors"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="gameDate",
            field=models.TextField(
                blank=True, default="", help_text="Game date (parsed from game text)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="gameSystem",
            field=models.TextField(
                blank=True, default="", help_text="Game system (parsed from game text)"
            ),
        ),
    ]
