# Generated by Django 5.1.6 on 2025-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0043_game_gamedate_game_gamesystem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="gameDate",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Game date (parsed from game text)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="gameSystem",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Game system (parsed from game text)",
                max_length=64,
            ),
        ),
    ]
