# Generated by Django 5.1.6 on 2025-05-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0044_alter_game_gamedate_alter_game_gamesystem"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="copyright",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Copyright (parsed from game text)",
                max_length=255,
            ),
        ),
    ]
