# Generated by Django 5.1.6 on 2025-05-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0045_game_copyright"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="campaignName",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Part of this campaign (parsed from game text)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="campaignPosition",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Case position in campaign (parsed from game text)",
                max_length=64,
            ),
        ),
    ]
