# Generated by Django 5.1.6 on 2025-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0046_game_campaignname_game_campaignposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="adminSortKey",
            field=models.CharField(
                blank=True,
                help_text="alphanumeric field to control default sorting when presenting game list",
                max_length=32,
                null=True,
            ),
        ),
    ]
