# Generated by Django 5.0.3 on 2024-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloadPageHtml",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Just type raw html here",
                        verbose_name="Html to be display on the Downloads page",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
