# Generated by Django 5.0.3 on 2024-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="aboutPageHtml",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Just type raw html here",
                verbose_name="Html to be display on the About page",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="homePageHtml",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Just type raw html here",
                verbose_name="Html to be display on the Home page",
            ),
        ),
    ]
