name: hlweb_personal

services:

  hlweb_priv:
    image: jreichler/${COMPOSE_PROJECT_NAME}:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: docker/${COMPOSE_PROJECT_NAME}/Dockerfile
      context: ../../
      tags:
        - jreichler/${COMPOSE_PROJECT_NAME}:v2.1

    #ATTN: This command will OVERRIDE any CMD in the Dockerfile; currently we use same values
    #command: /install_scripts/run_mainservices.sh

    restart: always


    volumes:
      - media_games:/media/games
      - db:/db
      - jrlogs:/jrlogs
      - letsencrypt:/etc/letsencrypt

    ports:
      # TIP: see also the Dockerfile for exposing ports
      - "80:80"
      # we dont use 8000 anymore
      - "8000:8000"

    environment:
      - COMPOSE_PROJECT_NAME



# create named volumes used above
volumes:
  media_games:
  db:
  jrlogs:
  letsencrypt: