# Generated by Django 5.0.3 on 2024-04-09 10:53

import django.db.models.deletion
import games.models
import games.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name of the game", max_length=50
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, default="", help_text="Game text"),
                ),
                (
                    "textHash",
                    models.CharField(
                        blank=True, default="", help_text="Hash of text", max_length=80
                    ),
                ),
                (
                    "isPublic",
                    models.BooleanField(help_text="Is game publicly visible?"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", help_text="Title of game", max_length=80
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtitle of game",
                        max_length=80,
                    ),
                ),
                (
                    "authors",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Author(s) of game (w/emails)",
                        max_length=255,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", help_text="Short description"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Version information",
                        max_length=32,
                    ),
                ),
                (
                    "versionDate",
                    models.CharField(
                        blank=True, default="", help_text="Version date", max_length=64
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, default="", help_text="Difficulty", max_length=32
                    ),
                ),
                (
                    "cautions",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Age rage, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expected playtime",
                        max_length=32,
                    ),
                ),
                (
                    "extraInfo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Extra information (credits, links, etc.)",
                    ),
                ),
                (
                    "buildLog",
                    models.TextField(blank=True, default="", help_text="Build Log"),
                ),
                (
                    "needsBuild",
                    models.BooleanField(help_text="Game was updated and needs rebuild"),
                ),
                (
                    "isBuildErrored",
                    models.BooleanField(
                        help_text="Was there an error on the last build?"
                    ),
                ),
                (
                    "buildDate",
                    models.DateTimeField(
                        blank=True, help_text="When was story last built?", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", help_text="File label", max_length=80
                    ),
                ),
                (
                    "filefield",
                    models.FileField(
                        upload_to=games.models.calculateGameFileUploadPathRuntimeRelative,
                        validators=[games.validators.validateGameFile],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
