# Generated by Django 5.0.3 on 2024-04-04 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of the game", max_length=50)),
                (
                    "text",
                    models.TextField(blank=True, default="", help_text="Game text"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the game",
                        max_length=50,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", help_text="Short description"
                    ),
                ),
                (
                    "information",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Long description, credits, links",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Version information",
                        max_length=32,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, default="", help_text="Difficulty", max_length=32
                    ),
                ),
                (
                    "cautions",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Age rage, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expected playtime",
                        max_length=32,
                    ),
                ),
                (
                    "buildLog",
                    models.TextField(blank=True, default="", help_text="Build Log"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
