# Generated by Django 5.0.3 on 2024-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="url",
            field=models.CharField(
                blank=True, default="", help_text="Homepage url", max_length=255
            ),
        ),
    ]
