# Generated by Django 5.0.3 on 2024-04-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gamefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="label",
            field=models.CharField(
                blank=True, default="", help_text="File label", max_length=80
            ),
        ),
    ]
