# Generated by Django 5.0.3 on 2024-04-09 04:32

import games.models
import games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gamefile_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefile",
            name="ispublic",
            field=models.BooleanField(
                default=True, help_text="Is game publicly visible?"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="filefield",
            field=models.FileField(
                upload_to=games.models.calculateGameFileUploadPathRuntime,
                validators=[games.validators.validateGameFile],
            ),
        ),
    ]
