# Generated by Django 5.0.3 on 2024-04-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_queuestatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamefile",
            name="label",
        ),
        migrations.AddField(
            model_name="gamefile",
            name="note",
            field=models.CharField(
                blank=True, default="", help_text="Note", max_length=80
            ),
        ),
    ]
