# Generated by Django 5.0.3 on 2024-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_gamefile_ispublic_alter_gamefile_filefield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamefile",
            name="ispublic",
        ),
        migrations.AddField(
            model_name="game",
            name="ispublic",
            field=models.BooleanField(
                default=True, help_text="Is game publicly visible?"
            ),
            preserve_default=False,
        ),
    ]
