# Generated by Django 5.0.3 on 2024-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_gamefile_gamefiletype_alter_gamefile_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="queueStatus",
        ),
        migrations.AddField(
            model_name="game",
            name="gameQueueStatus",
            field=models.CharField(
                choices=[
                    ("NON", "None"),
                    ("RUN", "Running"),
                    ("QUE", "Queued"),
                    ("ERR", "Errored"),
                    ("COM", "Completed"),
                ],
                default="NON",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="gamefile",
            name="gameFileType",
            field=models.CharField(
                choices=[("UP", "User Upload"), ("BT", "Built")],
                default="UP",
                max_length=3,
            ),
        ),
    ]
