# Generated by Django 5.0.3 on 2024-04-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_game_preferredformatlayout_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="gameQueueStatus",
            new_name="queueStatus",
        ),
    ]
