# Generated by Django 5.0.3 on 2024-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_game_gamename"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="buildStats",
            field=models.TextField(
                blank=True, default="", help_text="Computed build statistics"
            ),
        ),
    ]
