# Generated by Django 5.0.3 on 2024-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_remove_game_needsbuild_game_outofdatedebug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="publishDate",
            field=models.DateTimeField(
                blank=True, help_text="When was story last published?", null=True
            ),
        ),
    ]
