# Generated by Django 5.0.3 on 2024-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_game_publishdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="buildStats",
            new_name="leadStats",
        ),
        migrations.RemoveField(
            model_name="game",
            name="buildDate",
        ),
        migrations.RemoveField(
            model_name="game",
            name="buildLog",
        ),
        migrations.RemoveField(
            model_name="game",
            name="isBuildErrored",
        ),
        migrations.RemoveField(
            model_name="game",
            name="outOfDateDebug",
        ),
        migrations.RemoveField(
            model_name="game",
            name="outOfDateDraft",
        ),
        migrations.RemoveField(
            model_name="game",
            name="outOfDatePreferred",
        ),
        migrations.RemoveField(
            model_name="game",
            name="outOfDatePublished",
        ),
        migrations.RemoveField(
            model_name="game",
            name="queueDate",
        ),
        migrations.RemoveField(
            model_name="game",
            name="queueStatus",
        ),
        migrations.AddField(
            model_name="game",
            name="buildResultsJson",
            field=models.TextField(
                blank=True, default="", help_text="All build results as json string"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="isErrorInSettings",
            field=models.BooleanField(
                default=False, help_text="Was there an error parsing settings?"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="settingsStatus",
            field=models.TextField(
                blank=True, default="", help_text="Parsed dettings status"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="textHashChangeDate",
            field=models.DateTimeField(
                blank=True, help_text="Date game text last changed", null=True
            ),
        ),
    ]
