# Generated by Django 5.0.3 on 2024-05-22 20:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_alter_game_buildresultsjsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buildResultsJsonField",
            field=models.JSONField(
                blank=True,
                decoder=django.core.serializers.json.DjangoJSONEncoder,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="All build results as json",
            ),
        ),
    ]
