# Generated by Django 5.0.3 on 2024-05-29 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0024_alter_game_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid1,
                editable=False,
                help_text="Unique uuid used for file paths",
            ),
        ),
    ]
